# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: configure-dotnet
    jobs:
    - job: build-config
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build $(buildConfiguration)'
      - script: dotnet build --configuration $(buildConfiguration)
    - job: script
      steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'inline'
            script: 'print("In first stage, job two")'
  - stage: python-script
    jobs:
    - job: another-script
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: 'print("In second stage, job one")'
